from growwapi import GrowwAPI
import pyotp
import pandas as pd
from datetime import datetime

 
api_key = "eyJraWQiOiJaTUtjVXciLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjI1NTcwNDEwMDEsImlhdCI6MTc2ODY0MTAwMSwibmJmIjoxNzY4NjQxMDAxLCJzdWIiOiJ7XCJ0b2tlblJlZklkXCI6XCI0NzdhYjBjMS00YmQwLTRmOGYtYjUwOC1iMzIxNmJkNGUwNjRcIixcInZlbmRvckludGVncmF0aW9uS2V5XCI6XCJlMzFmZjIzYjA4NmI0MDZjODg3NGIyZjZkODQ5NTMxM1wiLFwidXNlckFjY291bnRJZFwiOlwiNGM2ZWNmZGEtNDVlOC00MTlmLWJhNDctYjIxNzk3MzY3MGZiXCIsXCJkZXZpY2VJZFwiOlwiZjFkM2UyMzktMzU1Yi01NjQ5LWJkZDAtYjA1OTdkZGNhYmVmXCIsXCJzZXNzaW9uSWRcIjpcIjRiMmNlNjY4LTc4NWMtNGYyOC04NTY0LWY0YzFhNjljYWNhY1wiLFwiYWRkaXRpb25hbERhdGFcIjpcIno1NC9NZzltdjE2WXdmb0gvS0EwYkNhRlFWWTdENDd3dWxOc3NscElTbmhSTkczdTlLa2pWZDNoWjU1ZStNZERhWXBOVi9UOUxIRmtQejFFQisybTdRPT1cIixcInJvbGVcIjpcImF1dGgtdG90cFwiLFwic291cmNlSXBBZGRyZXNzXCI6XCI0OS4yMDQuMTY0Ljg5LDE3Mi43MS4xOTguNjYsMzUuMjQxLjIzLjEyM1wiLFwidHdvRmFFeHBpcnlUc1wiOjI1NTcwNDEwMDE2OTd9IiwiaXNzIjoiYXBleC1hdXRoLXByb2QtYXBwIn0.SkjwtEj67e5e7oYJEMoIWi9XWUEqDR9nmoe9DnQgMfpzRj-86cSU3CDPVmbO3KWEciS1vdmAQLFYKRt-ha1hnQ"
secret = "y6ldThW@ZX7qUPa-a_I8Old*vFm*WgqC"
 
access_token = GrowwAPI.get_access_token(api_key=api_key, secret=secret)
# Use access_token to initiate GrowwAPI
groww = GrowwAPI(access_token)



historical_candles_response = groww.get_historical_candles(
    exchange=groww.EXCHANGE_NSE,
    segment=groww.SEGMENT_CASH,
    groww_symbol="NSE-WIPRO",
    start_time="2025-12-01 10:56:00",
    end_time="2025-12-24 12:00:00",
    candle_interval=groww.CANDLE_INTERVAL_MIN_30
)
print(historical_candles_response)
 